- hosts: localhost
  vars:
      ansible_python_interpreter: /usr/bin/python3

  tasks:

    - package:
        name: jq
        state: present
      become: yes

    - pip:
        name: ['openstacksdk','numpy']

    - shell:
        cmd: ansible-galaxy collection install openstack.cloud -p $HOME/.ansible/collections