- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    auth_data: {
      'auth_url': "{{ ansible_env.OS_AUTH_URL }}",
      'os_access_token': "{{ ansible_env.OS_ACCESS_TOKEN }}",
      'os_project_id': "{{ ansible_env.OS_PROJECT_ID }}",
      'os_auth_type': "{{ ansible_env.OS_AUTH_TYPE }}",
      'os_identity_provider': "{{ ansible_env.OS_IDENTITY_PROVIDER}}",
      'os_protocol': "{{ ansible_env.OS_PROTOCOL}}"
    }
  tasks:
    - set_fact:
        random_key_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    - import_tasks: 2.9/os_key.yaml
      vars:
        state: present
        project_id: "{{ hostvars['localhost']['project_id'] }}"
        auth_url: "{{ hostvars['localhost']['auth_url'] }}"
        access_token: "{{ access_token }}"
        token_type: v3oidcaccesstoken
        identity_provider: "{{ hostvars['localhost']['identity_provider'] }}"
        protocol: openid
        name: "sdia_{{ random_key_name }}"
#
#
    - local_action: copy content={{ key_output }} dest=/tmp/key_output.json
#
    - include_tasks: create_key.yaml
      vars:
        instance_name: "{{ item.key }}"
      loop: "{{ instances | dict2items }}"